services:
  graphhopper:
    image: israelhikingmap/graphhopper:10.0
    container_name: graphhopper
    ports:
      - "8989:8989"
    volumes:
      - ./routing-backend/graphhopper/thapar_map.osm:/data/thapar_map.osm
      - ./routing-backend/graphhopper/config.yml:/data/config.yml
    command: >
      --input /data/thapar_map.osm
      --config /data/config.yml
      --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: on-failure

  routing-backend:
      build:
        context: ./routing-backend/api
        dockerfile: api.Dockerfile
      container_name: routing-backend
      depends_on:
        graphhopper:
          condition: service_healthy
      environment:
        GRAPHHOPPER_BASE_URL: http://graphhopper:8989/route
      ports:
        - "5000:5000"